### ISSUE TITLE
Errore descrizione missione #8

### ISSUE THREAD

**Issue by DiegoTiSpiego** [ScrappyCocco/TheColonistsItalian#6]
nella campagna, missione 8 che la parte finale della frase " e accumulare %10000"
![accumulare](https://user-images.githubusercontent.com/55562703/65729181-ad278580-e0bd-11e9-9f39-f7420c26ef9f.PNG)

**Comment by ScrappyCocco** [comment]
Confermo l'errore

https://github.com/ScrappyCocco/TheColonistsItalian/blob/8a74a409ce74badc4a11159b9adf516ae2f62566/The_Colonists_Translation_Data_Italian_JSON.json#L17746

**Comment by ScrappyCocco** [comment]
Sistemato con $
