### ISSUE TITLE
traduzione mancante

### ISSUE THREAD

**Issue by giovanni-gvnn** [ScrappyCocco/TheColonistsItalian#9]
Traduzione mancante: "Change Expedition Type"

![20240425121008_missing](https://github.com/ScrappyCocco/TheColonistsItalian/assets/64377631/5b576c9e-1ad2-49aa-a63b-fd81c5b0c1f6)

**Comment by ScrappyCocco** [comment]
Che versione del gioco stai giocando? Sei su Steam? Stai usando un branch beta particolare? 
Il mio gioco ha quel tasto tradotto
![image](https://github.com/ScrappyCocco/TheColonistsItalian/assets/11294898/91718d3a-e303-487e-a878-a4d18759a290)

**Comment by giovanni-gvnn** [comment]
sto usando steam, non ho impostato nulla di strano e non dovrebbe essere una beta.
Piu tardi ti dico la versione.

**Comment by giovanni-gvnn** [comment]
1.8.0.12

**Comment by ScrappyCocco** [comment]
Sicuro di non avere per esempio il file di traduzione in locale in %userprofile%\appdata\LocalLow\Codebyfire Ltd\The Colonists?
Perché io lo vedo corretto e nel file è corretto quindi è strano

**Comment by giovanni-gvnn** [comment]
io non ce l'ho messo... se c'è, c'è andato da solo... stasera guardo...

**Comment by ScrappyCocco** [comment]
Se ti sembra tutto a posto puoi riprodurre il problema andando in Sandbox dove è facile avere tutto subito e costruire subito un porto con la costruzione istantanea per visualizzare il problema, e a quel punto fare il report bug così da avere un file report da mandargli? Perché la situazione è molto strana

**Comment by ScrappyCocco** [comment]
Nel dubbio fai anche una verifica dei file di Steam così per sicurezza

**Comment by giovanni-gvnn** [comment]
> Sicuro di non avere per esempio il file di traduzione in locale in %userprofile%\appdata\LocalLow\Codebyfire Ltd\The Colonists?
> Perché io lo vedo corretto e nel file è corretto quindi è strano

questo è il contenuto, ora provo sandbox

![immagine](https://github.com/ScrappyCocco/TheColonistsItalian/assets/64377631/6f7b842b-c600-4dfb-a32b-f87c3babf483)

**Comment by giovanni-gvnn** [comment]
Sandbox 
![Screenshot 2024-04-26 191803](https://github.com/ScrappyCocco/TheColonistsItalian/assets/64377631/16f0185d-59d4-4185-80ba-d4950324815a)

**Comment by giovanni-gvnn** [comment]
Sandbox dopo verifica files

![immagine](https://github.com/ScrappyCocco/TheColonistsItalian/assets/64377631/b3e30fa8-7896-49ce-b3a6-67b0c0b16ca7)

**Comment by giovanni-gvnn** [comment]
Sandbox dopo verifica files - porto grande

![immagine](https://github.com/ScrappyCocco/TheColonistsItalian/assets/64377631/66c6d0f0-81af-4700-985d-7225f983b2c6)

**Comment by giovanni-gvnn** [comment]
Bugreport inviato.

**Comment by ScrappyCocco** [comment]
```
codebyfire:
It looks like it was an issue with the text field, it should be fixed in the next version
I'm not sure why it would have been being translated at all
```
Aspettiamo il prossimo update e vediamo

**Comment by ScrappyCocco** [comment]
Quando hai tempo prova con il nuovo aggiornamento

**Comment by giovanni-gvnn** [comment]
Ora è a posto. Grazie !
